"""Integration tests for the build/query/export context-engine flow."""

from __future__ import annotations

import asyncio
import json
import subprocess
from pathlib import Path

from typer.testing import CliRunner

from gitlore.build import build_index
from gitlore.cli import app
from gitlore.config import GitloreConfig
from gitlore.export import load_export_bundle, write_exports
from gitlore.index import IndexStore
from gitlore.mcp_server import create_mcp_server
from gitlore.query import build_context, render_context


def _git(repo: Path, *args: str) -> None:
    subprocess.run(["git", "-C", str(repo), *args], capture_output=True, check=True)


def _commit(repo: Path, message: str) -> None:
    _git(repo, "add", ".")
    _git(repo, "commit", "-m", message)


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def _make_repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init")
    _git(repo, "config", "user.email", "test@test.com")
    _git(repo, "config", "user.name", "Test")

    _write(
        repo / "README.md",
        """# Test Repo

## Build & Run

uv sync --all-extras
uv run pytest -q

## Conventions

Use small, focused changes and keep retry tests up to date.
""",
    )
    _write(
        repo / "src" / "client.py",
        "def retry(count: int) -> int:\n    return count\n",
    )
    _write(
        repo / "tests" / "test_client.py",
        "from src.client import retry\n\n\ndef test_retry():\n    assert retry(1) == 1\n",
    )
    _commit(repo, "feat(client): add retry helper")

    _write(
        repo / "src" / "client.py",
        "def retry(count: int) -> int:\n    if count < 0:\n        return 0\n    return count\n",
    )
    _write(
        repo / "tests" / "test_client.py",
        "from src.client import retry\n\n\ndef test_retry():\n    assert retry(1) == 1\n\n\ndef test_retry_negative():\n    assert retry(-1) == 0\n",
    )
    _commit(repo, "fix(client): handle negative retry count")

    _write(
        repo / "src" / "client.py",
        "def retry(count: int, limit: int = 5) -> int:\n    if count < 0:\n        return 0\n    return min(count, limit)\n",
    )
    _write(
        repo / "tests" / "test_client.py",
        "from src.client import retry\n\n\ndef test_retry():\n    assert retry(1) == 1\n\n\ndef test_retry_negative():\n    assert retry(-1) == 0\n\n\ndef test_retry_limit():\n    assert retry(10, limit=3) == 3\n",
    )
    _commit(repo, "refactor(client): add retry limit")

    return repo


def test_build_creates_index_and_metadata(tmp_path: Path):
    repo = _make_repo(tmp_path)
    config = GitloreConfig()
    config.repo_path = str(repo)
    config.sources.github = False
    config.build.min_shared_commits = 1
    config.build.min_coupling_lift = 1.0

    metadata = build_index(config)

    assert metadata.total_commits_analyzed == 3
    assert metadata.fact_count > 0
    assert (repo / ".gitlore" / "index.db").exists()

    store = IndexStore(str(repo))
    try:
        assert store.has_index() is True
        loaded = store.get_build_metadata()
    finally:
        store.close()

    assert loaded is not None
    assert loaded.total_commits_analyzed == 3
    assert loaded.source_coverage.docs is True


def test_context_returns_related_files_and_suggested_tests(tmp_path: Path):
    repo = _make_repo(tmp_path)
    config = GitloreConfig()
    config.repo_path = str(repo)
    config.sources.github = False
    config.build.min_shared_commits = 1
    config.build.min_coupling_lift = 1.0
    build_index(config)

    bundle = build_context(
        config,
        task="fix retry bug",
        files=["src/client.py"],
        format_name="json",
    )

    assert bundle.intent.value == "bugfix"
    assert any(item.path == "tests/test_client.py" for item in bundle.related_files)
    assert "tests/test_client.py" in bundle.suggested_tests
    rendered = render_context(bundle, format_name="json", config=config)
    payload = json.loads(rendered)
    assert payload["task"] == "fix retry bug"


def test_export_writes_stable_artifacts(tmp_path: Path):
    repo = _make_repo(tmp_path)
    config = GitloreConfig()
    config.repo_path = str(repo)
    config.sources.github = False
    config.export.formats = ["agents_md", "report"]
    config.build.min_shared_commits = 1
    config.build.min_coupling_lift = 1.0
    build_index(config)

    bundle = load_export_bundle(config)
    written = write_exports(bundle, config)

    assert len(written) == 2
    agents = (repo / "AGENTS.md").read_text()
    report = (repo / "gitlore-report.md").read_text()
    assert "Use small, focused changes" in agents or "Use conventional commits" in agents
    assert "Generated by gitlore" in report


def test_cli_and_mcp_use_same_context_core(tmp_path: Path):
    repo = _make_repo(tmp_path)
    runner = CliRunner()

    result = runner.invoke(app, ["build", "--repo", str(repo)])
    assert result.exit_code == 0

    result = runner.invoke(
        app,
        [
            "context",
            "--repo",
            str(repo),
            "--task",
            "fix retry bug",
            "--files",
            "src/client.py",
            "--format",
            "json",
        ],
    )
    assert result.exit_code == 0
    payload = json.loads(result.stdout)
    assert payload["task"] == "fix retry bug"

    config = GitloreConfig()
    config.repo_path = str(repo)
    server = create_mcp_server(config)
    tool_result = asyncio.run(
        server._tool_manager.call_tool(
            "get_context",
            {
                "task": "fix retry bug",
                "files": ["src/client.py"],
                "format": "json",
            },
        )
    )
    tool_payload = json.loads(tool_result)
    assert tool_payload["task"] == payload["task"]
