"""Tests for output formatters."""

from __future__ import annotations

import re

import pytest

from gitlore.formatters.agents_md import format_agents_md
from gitlore.formatters.claude_md import format_claude_md
from gitlore.formatters.copilot_instructions import format_copilot_instructions
from gitlore.formatters.cursor_rules import format_cursor_rules
from gitlore.formatters.html import format_html
from gitlore.models import EvidencePoint, Finding, FindingCategory, FindingSeverity, SynthesisResult


@pytest.fixture
def sample_synthesis() -> SynthesisResult:
    """A SynthesisResult with structured findings."""
    return SynthesisResult(
        findings=[
            Finding(
                title="Architecture",
                category=FindingCategory.ARCHITECTURE,
                severity=FindingSeverity.HIGH,
                insight="`src/auth/session.ts` and `src/auth/login.ts` are tightly coupled (92% co-change rate).\nAlways update both together.",
                files=["src/auth/session.ts", "src/auth/login.ts"],
            ),
            Finding(
                title="Gotchas",
                category=FindingCategory.LANDMINE,
                severity=FindingSeverity.MEDIUM,
                insight="",
                evidence=[
                    EvidencePoint(source="hotspots", text="`src/api/routes.ts` is a churn hotspot (35% fix ratio). Add extra test coverage."),
                    EvidencePoint(source="code", text="Never modify files in `src/runtime/autogen/` directly."),
                ],
            ),
            Finding(
                title="Conventions",
                category=FindingCategory.CONVENTION,
                severity=FindingSeverity.LOW,
                insight="Use conventional commits with scope: `feat(auth): description`.",
            ),
        ],
        model_used="openrouter/anthropic/claude-opus-4-6",
    )


# ── CLAUDE.md tests ───────────────────────────────────────────────────────────


class TestClaudeMd:
    def test_has_header_comment(self, sample_synthesis: SynthesisResult):
        output = format_claude_md(sample_synthesis)
        assert output.startswith("<!-- Generated by gitlore on")
        assert "Do not edit manually" in output

    def test_has_date_in_header(self, sample_synthesis: SynthesisResult):
        output = format_claude_md(sample_synthesis)
        assert re.search(r"\d{4}-\d{2}-\d{2}", output)

    def test_content_is_included(self, sample_synthesis: SynthesisResult):
        output = format_claude_md(sample_synthesis)
        assert "## Architecture" in output
        assert "src/auth/session.ts" in output
        assert "## Gotchas" in output
        assert "## Conventions" in output

    def test_empty_content_minimal_output(self):
        empty = SynthesisResult()
        output = format_claude_md(empty)
        assert "<!-- Generated by gitlore on" in output
        assert "## " not in output


# ── AGENTS.md tests ───────────────────────────────────────────────────────────


class TestAgentsMd:
    def test_has_agents_md_header(self, sample_synthesis: SynthesisResult):
        output = format_agents_md(sample_synthesis)
        assert "# AGENTS.md" in output

    def test_has_gitlore_comment(self, sample_synthesis: SynthesisResult):
        output = format_agents_md(sample_synthesis)
        assert "<!-- Generated by gitlore on" in output

    def test_content_is_included(self, sample_synthesis: SynthesisResult):
        output = format_agents_md(sample_synthesis)
        assert "## Architecture" in output
        assert "src/auth/session.ts" in output

    def test_content_same_as_claude_md(self, sample_synthesis: SynthesisResult):
        claude = format_claude_md(sample_synthesis)
        agents = format_agents_md(sample_synthesis)
        # Both should contain the same synthesis content
        assert "src/auth/session.ts" in claude
        assert "src/auth/session.ts" in agents


# ── .cursorrules tests ────────────────────────────────────────────────────────


class TestCursorRules:
    def test_has_yaml_frontmatter(self, sample_synthesis: SynthesisResult):
        output = format_cursor_rules(sample_synthesis)
        assert output.startswith("---\n")
        second_fence = output.index("---", 4)
        assert second_fence > 0

    def test_frontmatter_has_description(self, sample_synthesis: SynthesisResult):
        output = format_cursor_rules(sample_synthesis)
        assert "description:" in output

    def test_frontmatter_has_always_apply(self, sample_synthesis: SynthesisResult):
        output = format_cursor_rules(sample_synthesis)
        assert "alwaysApply: true" in output

    def test_content_after_frontmatter(self, sample_synthesis: SynthesisResult):
        output = format_cursor_rules(sample_synthesis)
        second_fence = output.index("---", 4)
        content_start = output.index("## Architecture")
        assert content_start > second_fence


# ── copilot-instructions.md tests ─────────────────────────────────────────────


class TestCopilotInstructions:
    def test_has_copilot_header(self, sample_synthesis: SynthesisResult):
        output = format_copilot_instructions(sample_synthesis)
        assert "# GitHub Copilot Instructions" in output

    def test_has_gitlore_comment(self, sample_synthesis: SynthesisResult):
        output = format_copilot_instructions(sample_synthesis)
        assert "<!-- Generated by gitlore on" in output

    def test_content_is_included(self, sample_synthesis: SynthesisResult):
        output = format_copilot_instructions(sample_synthesis)
        assert "## Architecture" in output
        assert "src/auth/session.ts" in output


# ── HTML report tests ────────────────────────────────────────────────────────


class TestHtml:
    def test_has_doctype(self, sample_synthesis: SynthesisResult):
        output = format_html(sample_synthesis)
        assert output.startswith("<!DOCTYPE html>")

    def test_has_finding_titles(self, sample_synthesis: SynthesisResult):
        output = format_html(sample_synthesis)
        assert "Architecture" in output
        assert "Gotchas" in output
        assert "Conventions" in output

    def test_has_category_headers(self, sample_synthesis: SynthesisResult):
        output = format_html(sample_synthesis)
        assert "Landmines" in output
        assert "Code Patterns" not in output  # no findings in this category
