"""Deterministic docs and config extraction for the context index."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


_MARKDOWN_PATTERNS = [
    "README*",
    "AGENTS.md",
    "CLAUDE.md",
    "CONTRIBUTING*",
]
_CONFIG_PATTERNS = [
    "pyproject.toml",
    "package.json",
    "Makefile",
    "justfile",
]
_WORKFLOW_GLOB = ".github/workflows/*.yml"

_COMMAND_RE = re.compile(
    r"(?im)^\s*(?:uv|python|pytest|ruff|mypy|npm|pnpm|yarn|make|just)\b.*$"
)


@dataclass
class DocSnippet:
    path: str
    title: str
    content: str
    source_type: str


def iter_doc_paths(repo_path: str) -> list[Path]:
    """Collect the supported doc/config file set for v1 indexing."""
    repo = Path(repo_path)
    paths: set[Path] = set()
    for pattern in _MARKDOWN_PATTERNS + _CONFIG_PATTERNS:
        paths.update(repo.glob(pattern))
    docs_dir = repo / "docs"
    if docs_dir.exists():
        paths.update(docs_dir.rglob("*.md"))
    workflow_dir = repo / ".github" / "workflows"
    if workflow_dir.exists():
        paths.update(workflow_dir.glob("*.yml"))
    deduped: dict[Path, Path] = {}
    for path in paths:
        if path.is_file():
            deduped[path.resolve()] = path
    return sorted(deduped.values())


def extract_doc_snippets(repo_path: str) -> list[DocSnippet]:
    """Extract deterministic doc/config snippets suitable for indexing."""
    snippets: list[DocSnippet] = []
    repo = Path(repo_path)
    for path in iter_doc_paths(repo_path):
        rel_path = str(path.relative_to(repo))
        raw = path.read_text()
        if raw.startswith("<!-- Generated by gitlore"):
            continue
        if path.suffix.lower() == ".md":
            snippets.extend(_extract_markdown(rel_path, raw))
        else:
            snippets.extend(_extract_config(rel_path, raw))
    return snippets


def _extract_markdown(path: str, text: str) -> list[DocSnippet]:
    if not text.strip():
        return []

    headings = list(re.finditer(r"(?m)^#{1,3}\s+(.+)$", text))
    if not headings:
        return [DocSnippet(path=path, title=Path(path).stem, content=_trim(text), source_type="doc")]

    snippets: list[DocSnippet] = []
    for idx, match in enumerate(headings):
        start = match.end()
        end = headings[idx + 1].start() if idx + 1 < len(headings) else len(text)
        body = _trim(text[start:end])
        if not body:
            continue
        title = match.group(1).strip()
        command_lines = "\n".join(_COMMAND_RE.findall(body))
        content = body if len(body) <= 800 else body[:800].strip()
        if command_lines:
            content = f"{content}\n\nCommands:\n{command_lines}".strip()
        snippets.append(
            DocSnippet(
                path=path,
                title=title,
                content=content,
                source_type="doc",
            )
        )
    return snippets


def _extract_config(path: str, text: str) -> list[DocSnippet]:
    commands = _COMMAND_RE.findall(text)
    first_lines = "\n".join(text.splitlines()[:40]).strip()
    content = first_lines
    if commands:
        content = f"{content}\n\nCommands:\n" + "\n".join(commands)
    content = _trim(content)
    if not content:
        return []
    return [
        DocSnippet(
            path=path,
            title=Path(path).name,
            content=content[:800],
            source_type="config",
        )
    ]


def _trim(text: str) -> str:
    return re.sub(r"\n{3,}", "\n\n", text.strip())
