"""Render stable facts from the knowledge index into export artifacts."""

from __future__ import annotations

from datetime import date
from pathlib import Path

from gitlore.config import GitloreConfig
from gitlore.index import IndexStore
from gitlore.models import ExportBundle, FactKind, KnowledgeFact, KnowledgeSeverity


def load_export_bundle(config: GitloreConfig) -> ExportBundle:
    """Load stable export facts from the current index."""
    store = IndexStore(config.repo_path)
    try:
        if not store.has_index():
            raise FileNotFoundError("No gitlore index found. Run `gitlore build` first.")
        facts = store.load_facts()
        metadata = store.get_build_metadata()
    finally:
        store.close()

    selected = _select_export_facts(facts)
    return ExportBundle(facts=selected, build_metadata=metadata)


def write_exports(bundle: ExportBundle, config: GitloreConfig) -> list[str]:
    """Write the configured export formats to disk."""
    repo = Path(config.repo_path)
    output_map = {
        "agents_md": ("AGENTS.md", render_agents_md),
        "claude_md": ("CLAUDE.md", render_claude_md),
        "cursor_rules": (".cursor/rules/gitlore.mdc", render_cursor_rules),
        "copilot_instructions": (".github/copilot-instructions.md", render_copilot_instructions),
        "report": ("gitlore-report.md", render_report),
        "html": ("gitlore-report.html", render_html),
    }
    written: list[str] = []
    for format_name in config.export.formats:
        if format_name not in output_map:
            continue
        rel_path, renderer = output_map[format_name]
        out_path = repo / rel_path
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(renderer(bundle))
        written.append(str(out_path))
    return written


def render_agents_md(bundle: ExportBundle) -> str:
    header = _header_comment(bundle)
    body = _render_instruction_blocks(bundle)
    return f"{header}\n\n# AGENTS.md\n\n{body}\n"


def render_claude_md(bundle: ExportBundle) -> str:
    return f"{_header_comment(bundle)}\n\n{_render_instruction_blocks(bundle)}\n"


def render_cursor_rules(bundle: ExportBundle) -> str:
    today = _build_date(bundle)
    body = _render_instruction_blocks(bundle)
    return (
        "---\n"
        f"description: Repository-specific coding rules generated by gitlore on {today}\n"
        "globs:\n"
        "alwaysApply: true\n"
        "---\n\n"
        f"{body}\n"
    )


def render_copilot_instructions(bundle: ExportBundle) -> str:
    return (
        f"{_header_comment(bundle)}\n\n"
        "# GitHub Copilot Instructions\n\n"
        f"{_render_instruction_blocks(bundle)}\n"
    )


def render_report(bundle: ExportBundle) -> str:
    lines = [f"<!-- Generated by gitlore on {_build_date(bundle)} -->", ""]
    for fact in bundle.facts:
        lines.append(f"## {fact.title}")
        lines.append("")
        lines.append(fact.guidance)
        if fact.files:
            lines.append("")
            lines.append("Files: " + ", ".join(f"`{path}`" for path in fact.files))
        if fact.evidence:
            lines.append("")
            for evidence in fact.evidence[:3]:
                lines.append(f"- {evidence.source_type}: {evidence.excerpt}")
        lines.append("")
    return "\n".join(lines).strip() + "\n"


def render_html(bundle: ExportBundle) -> str:
    cards = []
    for fact in bundle.facts:
        evidence_html = "".join(
            f"<li><strong>{evidence.source_type}</strong>: {evidence.excerpt}</li>"
            for evidence in fact.evidence[:3]
        )
        files_html = ", ".join(fact.files)
        cards.append(
            "<article>"
            f"<h2>{fact.title}</h2>"
            f"<p>{fact.guidance}</p>"
            f"<p><small>{files_html}</small></p>"
            f"<ul>{evidence_html}</ul>"
            "</article>"
        )
    return (
        "<!DOCTYPE html><html><head><meta charset='utf-8'>"
        "<title>gitlore report</title>"
        "<style>body{font-family:system-ui;padding:2rem;max-width:960px;margin:auto}"
        "article{border:1px solid #ddd;padding:1rem;margin-bottom:1rem;border-radius:10px}"
        "small{color:#666}</style></head><body>"
        f"<h1>gitlore export</h1><p>Built {_build_date(bundle)}</p>{''.join(cards)}</body></html>"
    )


def _select_export_facts(facts: list[KnowledgeFact]) -> list[KnowledgeFact]:
    allowed_doc_titles = {"build", "run", "convention", "environment", "config"}
    stable = [
        fact
        for fact in facts
        if fact.kind == FactKind.RULE
        or (
            fact.kind == FactKind.DOC_GUIDANCE
            and any(token in fact.title.lower() for token in allowed_doc_titles)
        )
    ]
    landmines = [
        fact
        for fact in facts
        if fact.kind == FactKind.FRAGILE_AREA and fact.severity == KnowledgeSeverity.HIGH
    ][:2]
    selected = sorted(stable, key=lambda fact: (fact.kind.value, fact.title))
    selected.extend(landmines)
    return selected


def _render_instruction_blocks(bundle: ExportBundle) -> str:
    if not bundle.facts:
        return ""
    lines: list[str] = []
    for fact in bundle.facts:
        lines.append(f"## {fact.title}")
        lines.append("")
        lines.append(fact.guidance)
        if fact.files:
            lines.append("")
            lines.append("Files: " + ", ".join(f"`{path}`" for path in fact.files))
        lines.append("")
    return "\n".join(lines).strip()


def _header_comment(bundle: ExportBundle) -> str:
    return f"<!-- Generated by gitlore on {_build_date(bundle)}. Do not edit manually. -->"


def _build_date(bundle: ExportBundle) -> str:
    if bundle.build_metadata is not None:
        return bundle.build_metadata.built_at.date().isoformat()
    return date.today().isoformat()
