"""Render knowledge notes from the index into export artifacts."""

from __future__ import annotations

from datetime import date
from pathlib import Path

from gitlore.config import GitloreConfig
from gitlore.index import IndexStore
from gitlore.models import ExportBundle, KnowledgeNote


def load_export_bundle(config: GitloreConfig) -> ExportBundle:
    """Load stable repo-wide knowledge notes from the current index."""
    store = IndexStore(config.repo_path)
    try:
        if not store.has_index():
            raise FileNotFoundError("No gitlore index found. Run `gitlore build` first.")
        notes = store.load_notes()
        metadata = store.get_build_metadata()
    finally:
        store.close()

    selected = _select_export_notes(notes)
    return ExportBundle(notes=selected, build_metadata=metadata)


def write_exports(bundle: ExportBundle, config: GitloreConfig) -> list[str]:
    """Write the configured export formats to disk."""
    repo = Path(config.repo_path)
    output_map = {
        "agents_md": ("AGENTS.md", render_agents_md),
        "claude_md": ("CLAUDE.md", render_claude_md),
        "cursor_rules": (".cursor/rules/gitlore.mdc", render_cursor_rules),
        "copilot_instructions": (".github/copilot-instructions.md", render_copilot_instructions),
        "report": ("gitlore-report.md", render_report),
        "html": ("gitlore-report.html", render_html),
    }
    written: list[str] = []
    for format_name in config.export.formats:
        if format_name not in output_map:
            continue
        rel_path, renderer = output_map[format_name]
        out_path = repo / rel_path
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(renderer(bundle))
        written.append(str(out_path))
    return written


def render_agents_md(bundle: ExportBundle) -> str:
    return f"{_header_comment(bundle)}\n\n# AGENTS.md\n\n{_render_notes(bundle.notes)}\n"


def render_claude_md(bundle: ExportBundle) -> str:
    return f"{_header_comment(bundle)}\n\n{_render_notes(bundle.notes)}\n"


def render_cursor_rules(bundle: ExportBundle) -> str:
    today = _build_date(bundle)
    return (
        "---\n"
        f"description: Repository knowledge generated by gitlore on {today}\n"
        "globs:\n"
        "alwaysApply: true\n"
        "---\n\n"
        f"{_render_notes(bundle.notes)}\n"
    )


def render_copilot_instructions(bundle: ExportBundle) -> str:
    return (
        f"{_header_comment(bundle)}\n\n"
        "# GitHub Copilot Instructions\n\n"
        f"{_render_notes(bundle.notes)}\n"
    )


def render_report(bundle: ExportBundle) -> str:
    lines = [f"<!-- Generated by gitlore on {_build_date(bundle)} -->", ""]
    for note in bundle.notes:
        lines.append(f"## [{note.confidence}]")
        lines.append("")
        lines.append(note.text)
        if note.evidence_refs:
            lines.append("")
            lines.append("Evidence: " + ", ".join(note.evidence_refs[:3]))
        lines.append("")
    return "\n".join(lines).strip() + "\n"


def render_html(bundle: ExportBundle) -> str:
    notes_html = []
    for note in bundle.notes:
        refs = ", ".join(note.evidence_refs[:3])
        notes_html.append(
            "<article>"
            f"<h2>{note.confidence}</h2>"
            f"<p>{note.text}</p>"
            f"<p><small>{refs}</small></p>"
            "</article>"
        )
    return (
        "<!DOCTYPE html><html><head><meta charset='utf-8'>"
        "<title>gitlore knowledge</title>"
        "<style>body{font-family:system-ui;padding:2rem;max-width:960px;margin:auto}"
        "article{border:1px solid #ddd;padding:1rem;margin-bottom:1rem;border-radius:10px}"
        "small{color:#666}</style></head><body>"
        f"<h1>gitlore knowledge</h1><p>Built {_build_date(bundle)}</p>"
        f"{''.join(notes_html)}</body></html>"
    )


def _select_export_notes(notes: list[KnowledgeNote]) -> list[KnowledgeNote]:
    """Select notes suitable for repo-wide export."""
    repo_wide = [n for n in notes if not n.anchors and n.confidence in ("high", "medium")]
    high_confidence = [n for n in notes if n.confidence == "high" and n not in repo_wide]
    selected = repo_wide + high_confidence
    return selected[:12]


def _render_notes(notes: list[KnowledgeNote]) -> str:
    if not notes:
        return ""
    lines: list[str] = []
    for note in notes:
        lines.append(f"- {note.text}")
        if note.evidence_refs:
            lines.append(f"  Evidence: {', '.join(note.evidence_refs[:3])}")
        lines.append("")
    return "\n".join(lines).strip()


def _header_comment(bundle: ExportBundle) -> str:
    return f"<!-- Generated by gitlore on {_build_date(bundle)}. Do not edit manually. -->"


def _build_date(bundle: ExportBundle) -> str:
    if bundle.build_metadata is not None:
        return bundle.build_metadata.built_at.date().isoformat()
    return date.today().isoformat()
