"""Render stable advice cards from the planning index into export artifacts."""

from __future__ import annotations

from datetime import date
from pathlib import Path

from gitlore.config import GitloreConfig
from gitlore.index import IndexStore
from gitlore.models import AdviceCard, AdviceKind, AdvicePriority, ExportBundle, QueryIntent


def load_export_bundle(config: GitloreConfig) -> ExportBundle:
    """Load stable repo-wide guidance cards from the current index."""
    store = IndexStore(config.repo_path)
    try:
        if not store.has_index():
            raise FileNotFoundError("No gitlore index found. Run `gitlore build` first.")
        cards = store.load_cards()
        metadata = store.get_build_metadata()
    finally:
        store.close()

    selected = _select_export_cards(cards)
    return ExportBundle(cards=selected, build_metadata=metadata)


def write_exports(bundle: ExportBundle, config: GitloreConfig) -> list[str]:
    """Write the configured export formats to disk."""
    repo = Path(config.repo_path)
    output_map = {
        "agents_md": ("AGENTS.md", render_agents_md),
        "claude_md": ("CLAUDE.md", render_claude_md),
        "cursor_rules": (".cursor/rules/gitlore.mdc", render_cursor_rules),
        "copilot_instructions": (".github/copilot-instructions.md", render_copilot_instructions),
        "report": ("gitlore-report.md", render_report),
        "html": ("gitlore-report.html", render_html),
    }
    written: list[str] = []
    for format_name in config.export.formats:
        if format_name not in output_map:
            continue
        rel_path, renderer = output_map[format_name]
        out_path = repo / rel_path
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(renderer(bundle))
        written.append(str(out_path))
    return written


def render_agents_md(bundle: ExportBundle) -> str:
    return f"{_header_comment(bundle)}\n\n# AGENTS.md\n\n{_render_cards(bundle.cards)}\n"


def render_claude_md(bundle: ExportBundle) -> str:
    return f"{_header_comment(bundle)}\n\n{_render_cards(bundle.cards)}\n"


def render_cursor_rules(bundle: ExportBundle) -> str:
    today = _build_date(bundle)
    return (
        "---\n"
        f"description: Repository planning guidance generated by gitlore on {today}\n"
        "globs:\n"
        "alwaysApply: true\n"
        "---\n\n"
        f"{_render_cards(bundle.cards)}\n"
    )


def render_copilot_instructions(bundle: ExportBundle) -> str:
    return (
        f"{_header_comment(bundle)}\n\n"
        "# GitHub Copilot Instructions\n\n"
        f"{_render_cards(bundle.cards)}\n"
    )


def render_report(bundle: ExportBundle) -> str:
    lines = [f"<!-- Generated by gitlore on {_build_date(bundle)} -->", ""]
    for card in bundle.cards:
        lines.append(f"## [{card.priority.value}] {card.kind.value}")
        lines.append("")
        lines.append(card.text)
        refs = [item.ref for item in card.evidence[:3]]
        if refs:
            lines.append("")
            lines.append("Refs: " + ", ".join(refs))
        lines.append("")
    return "\n".join(lines).strip() + "\n"


def render_html(bundle: ExportBundle) -> str:
    cards_html = []
    for card in bundle.cards:
        refs = ", ".join(item.ref for item in card.evidence[:3])
        cards_html.append(
            "<article>"
            f"<h2>{card.kind.value} / {card.priority.value}</h2>"
            f"<p>{card.text}</p>"
            f"<p><small>{refs}</small></p>"
            "</article>"
        )
    return (
        "<!DOCTYPE html><html><head><meta charset='utf-8'>"
        "<title>gitlore guidance</title>"
        "<style>body{font-family:system-ui;padding:2rem;max-width:960px;margin:auto}"
        "article{border:1px solid #ddd;padding:1rem;margin-bottom:1rem;border-radius:10px}"
        "small{color:#666}</style></head><body>"
        f"<h1>gitlore guidance</h1><p>Built {_build_date(bundle)}</p>{''.join(cards_html)}</body></html>"
    )


def _select_export_cards(cards: list[AdviceCard]) -> list[AdviceCard]:
    repo_guidance = [
        card
        for card in cards
        if card.kind in {AdviceKind.CONVENTION, AdviceKind.REVIEW}
        and (not card.anchors or QueryIntent.GENERAL in card.applies_to)
        and card.priority != AdvicePriority.LOW
    ]
    landmines = [
        card
        for card in cards
        if card.kind in {AdviceKind.RISK, AdviceKind.HISTORICAL}
        and not card.anchors
        and card.priority == AdvicePriority.HIGH
    ]
    selected: list[AdviceCard] = []
    for card in repo_guidance + landmines:
        if card not in selected:
            selected.append(card)
    return selected[:12]


def _render_cards(cards: list[AdviceCard]) -> str:
    if not cards:
        return ""
    lines: list[str] = []
    for card in cards:
        lines.append(f"## {card.kind.value.title()} [{card.priority.value}]")
        lines.append("")
        lines.append(card.text)
        refs = [item.ref for item in card.evidence[:3]]
        if refs:
            lines.append("")
            lines.append("Refs: " + ", ".join(refs))
        lines.append("")
    return "\n".join(lines).strip()


def _header_comment(bundle: ExportBundle) -> str:
    return f"<!-- Generated by gitlore on {_build_date(bundle)}. Do not edit manually. -->"


def _build_date(bundle: ExportBundle) -> str:
    if bundle.build_metadata is not None:
        return bundle.build_metadata.built_at.date().isoformat()
    return date.today().isoformat()
