"""Format synthesis output as AGENTS.md (open standard for AI coding agents)."""

from __future__ import annotations

from datetime import date

from gitlore.models import SynthesisResult


def format_agents_md(result: SynthesisResult) -> str:
    """Format a SynthesisResult as AGENTS.md content."""
    today = date.today().isoformat()
    lines = [
        f"<!-- Generated by gitlore on {today}. Do not edit manually. -->",
        "",
        "# AGENTS.md",
        "",
    ]
    if result.content:
        lines.append(result.content)
    lines.append("")
    return "\n".join(lines)
