"""Format synthesis output as CLAUDE.md for Claude Code."""

from __future__ import annotations

from datetime import date

from gitlore.models import SynthesisResult


def format_claude_md(result: SynthesisResult) -> str:
    """Format a SynthesisResult as CLAUDE.md content."""
    today = date.today().isoformat()
    header = f"<!-- Generated by gitlore on {today}. Do not edit manually. -->"
    if not result.content:
        return header + "\n"
    return f"{header}\n\n{result.content}\n"
