"""Format synthesis output as .github/copilot-instructions.md for GitHub Copilot."""

from __future__ import annotations

from datetime import date

from gitlore.models import SynthesisResult


def format_copilot_instructions(result: SynthesisResult) -> str:
    """Format a SynthesisResult as copilot-instructions.md content."""
    today = date.today().isoformat()
    lines = [
        f"<!-- Generated by gitlore on {today}. Do not edit manually. -->",
        "",
        "# GitHub Copilot Instructions",
        "",
    ]
    if result.content:
        lines.append(result.content)
    lines.append("")
    return "\n".join(lines)
