"""Format synthesis output as .cursorrules (MDC format with YAML frontmatter)."""

from __future__ import annotations

from datetime import date

from gitlore.models import SynthesisResult


def format_cursor_rules(result: SynthesisResult) -> str:
    """Format a SynthesisResult as .cursorrules MDC content."""
    today = date.today().isoformat()
    lines = [
        "---",
        f"description: Repository-specific coding guidelines generated by gitlore on {today}",
        "globs:",
        "alwaysApply: true",
        "---",
        "",
    ]
    if result.content:
        lines.append(result.content)
    lines.append("")
    return "\n".join(lines)
