"""Format synthesis findings as a standalone knowledge report."""

from __future__ import annotations

from datetime import date

from gitlore.models import Finding, FindingCategory, SynthesisResult

# Group findings by category in this display order
_CATEGORY_ORDER = [
    FindingCategory.FRAGILE_AREA,
    FindingCategory.LANDMINE,
    FindingCategory.ARCHITECTURE,
    FindingCategory.CODE_PATTERN,
    FindingCategory.CONVENTION,
    FindingCategory.TOOLING,
]

_CATEGORY_LABELS = {
    FindingCategory.FRAGILE_AREA: "Fragile Areas",
    FindingCategory.LANDMINE: "Landmines",
    FindingCategory.ARCHITECTURE: "Architecture",
    FindingCategory.CODE_PATTERN: "Code Patterns",
    FindingCategory.CONVENTION: "Conventions",
    FindingCategory.TOOLING: "Tooling",
}


def _render_finding(f: Finding) -> str:
    """Render a single finding as markdown."""
    lines = [f"### {f.title}"]
    if f.insight:
        lines.append("")
        lines.append(f.insight)
    if f.files:
        lines.append("")
        lines.append("**Files:** " + ", ".join(f"`{p}`" for p in f.files))
    if f.evidence:
        lines.append("")
        for e in f.evidence:
            lines.append(f"- *{e.source}:* {e.text}")
    return "\n".join(lines)


def format_report(result: SynthesisResult) -> str:
    """Format a SynthesisResult as a knowledge report."""
    today = date.today().isoformat()
    commits = result.analysis.total_commits_analyzed if result.analysis else 0
    review_flag = "with PR review data" if result.has_review_data else "git history only"

    lines = [f"<!-- Generated by gitlore on {today} | {commits} commits analyzed | {review_flag} -->"]

    if not result.findings:
        return "\n".join(lines) + "\n"

    # Group by category
    by_category: dict[FindingCategory, list[Finding]] = {}
    for f in result.findings:
        by_category.setdefault(f.category, []).append(f)

    for cat in _CATEGORY_ORDER:
        findings = by_category.get(cat)
        if not findings:
            continue
        lines.append("")
        lines.append(f"## {_CATEGORY_LABELS[cat]}")
        for f in findings:
            lines.append("")
            lines.append(_render_finding(f))

    return "\n".join(lines) + "\n"
