"""Format synthesis output as a standalone knowledge report."""

from __future__ import annotations

from datetime import date

from gitlore.models import SynthesisResult


def format_report(result: SynthesisResult) -> str:
    """Format a SynthesisResult as a knowledge report."""
    today = date.today().isoformat()
    commits = result.analysis.total_commits_analyzed if result.analysis else 0
    review_flag = "with PR review data" if result.has_review_data else "git history only"

    header = f"<!-- Generated by gitlore on {today} | {commits} commits analyzed | {review_flag} -->"
    if not result.content:
        return header + "\n"
    return f"{header}\n\n{result.content}\n"
